appHost: www.yourwiki.com
appKey: thisIsAppKey
# allowHttp: false
azuread:
    enabled: true
    tenantId: 5a5e106e-7166-11ea-bc55-0242ac130003
    appId: 6667181a-7166-11ea-bc55-0242ac130003
    appSecret: thisIsSecret
smtp:
    enabled: true
    host: smtp.yourwiki.com
    port: "25"
    username: user
    password: thisIsPassword
    fromAddress: do_not_reply@yourwiki.com
    fromName: "My Wiki"